config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'welcome#index'
  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :destroy, :accept] do 
  	member do
  		put :accept
  	end
  end

  resources :posts, only: [:create, :update, :edit, :destroy]
  resources :activities, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	include PublicActivity::Model
	belongs_to :user
	belongs_to :friend, class_name: "User"

	def accept_friendship
		self.update_attributes(state: "active", friended_at: Time.now)
	end

	def deny_friendship
		self.destroy
	end

	def cancel_friendship
		self.destroy
	end
end

app/models/post.rb
class Post < ApplicationRecord
	include PublicActivity::Model
	
	belongs_to :user
	validates :user_id, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  
  has_many :posts, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy

  def request_friendship(user_2)
  	self.friendships.create(friend: user_2)
  end

  def active_friends
  	self.friendships.where(state: "active").map(&:friend) + self.inverse_friendships.where(state: "active").map(&:user)
  end

  def pending_friend_requests_from
  	self.inverse_friendships.where(state: "pending").map(&:user)
  end

  def pending_friend_requests_to
  	self.friendships.where(state: "pending").map(&:friend)
  end

  def friendship_status(user_2)
  	friendship = Friendship.where(user_id: [self.id, user_2.id], friend_id: [self.id, user_2.id])
  	if friendship.any? == false
  		return "not_friends"
  	elsif friendship.first.state == "active"
  		return "friends"
  	elsif friendship.first.user == self
  		return "pending"
  	elsif friendship.first.friend == self
  		return "requested"
  	end
  end

  def friendship_relation(user_2)
    Friendship.where(user_id: [self.id, user_2.id], friend_id: [self.id, user_2.id]).first
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
before_action :authenticate_user!

	def index
		@users = current_user.active_friends
		@users.push(current_user)
		@activities = PublicActivity::Activity.where(owner_id: @users).order('created_at DESC')
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :age, :bio, :school, :work])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :age, :bio, :school, :work])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :set_user, only: [:create]
	before_action :set_friendship, only: [:destroy, :accept]
	before_action :authenticate_user!

	def create
		@friendship = current_user.request_friendship(@user)

		respond_to do |format|
			format.html {redirect_to users_path, notice: "Friendship Requested!"}
		end
	end

	def accept
		@friendship.accept_friendship
		@friendship.create_activity key: "friendship.accepted", owner: @friendship.user, recipient: @friendship.friend
		@friendship.create_activity key: "friendship.accepted", owner: @friendship.friend, recipient: @friendship.user

		respond_to do |format|
			format.html {redirect_to users_path, notice: "Congrats, new Friends!"}
		end
	end

	def destroy
		@friendship.destroy

		respond_to do |format|
			format.html {redirect_to users_path, notice: "Bad Friend, eh?"}
		end
	end

	private

	def set_friendship
		@friendship = Friendship.find(params[:id])
	end

	def set_user
		@user = User.find(params[:user_id])
	end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:edit, :update, :destroy]
	
	def create
		@post = current_user.posts.new(post_params)


		if @post.save
			@post.create_activity key: 'post.created', owner: @post.user
			
			respond_to do |format|
				format.html {redirect_to user_path(@post.user.username), notice: "Post Created"}
			end
		else
			redirect_to user_path(@post.user.username), notice: "Uh oh! What happened?"
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			respond_to do |format|
				format.html {redirect_to user_path(@post.user.username), notice: "Post Updated!"}
			end
		else
			redirect_to post_path(@post), notice: "Uh oh! What happened?"
		end
	end

	def destroy
		@post.destroy

		respond_to do |format|
			format.html {redirect_to user_path(@post.user.username), notice: "Thank you for deleting your senseless post."}
		end
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:user_id, :content)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show]
  
  def index
  	case params[:people]
  		when "friends"
  		@users = current_user.active_friends
  		when "requests"
  		@users = current_user.pending_friend_requests_from
  		when "pending"
  		@users = current_user.pending_friend_requests_to
  		else
  		@users = User.where.not(id: current_user.id)
  	end	

  end

  def show
    @post = Post.new
    @posts = @user.posts.order('created_at DESC')
  	@activities = PublicActivity::Activity.where(owner_id: @user.id)
  end



  def set_user
  	@user = User.find_by(username: params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if current_user
  		redirect_to activities_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
		case flash_type
			when "success"
				"alert-success"
			when "error"
				"alert-danger"
			when "alert"
				"alert-warning"
			when "notice"
				"alert-info"
			else
				flash_type.to_s
		end

	end 


end #module END

app/helpers/users_helper.rb
module UsersHelper

	def friend_buttons(user)
		case current_user.friendship_status(user)
			when "not_friends"
				link_to "Add Friend", friendships_path(user_id: user.id), method: :post
			when "friends"
				link_to "Remove Friend", friendship_path(current_user.friendship_relation(user)), method: :delete
			when "pending"
				link_to "Cancel Request", friendship_path(current_user.friendship_relation(user)), method: :delete
			when "requested"
				accept = link_to "Deny", friendship_path(current_user.friendship_relation(user)), method: :delete
				deny = link_to "Accept", accept_friendship_path(current_user.friendship_relation(user)), method: :put
				return accept + " | " + deny
		end
	end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/index.html.erb
<div class="jumbotron text-center">
	<h1>Timeline</h1>
</div>

<div class="container">
<% @activities.each do |activity| %>
	<% unless activity.trackable_type == "Friendship" && activity.owner == current_user %>
		<% if activity.trackable %>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="panel panel-default">

						<div class="panel-heading">
							<div class="media">
								<div class="pull-left">
									<%= gravatar_tag activity.owner.email, size: 55 %>
								</div>
								<div>
									<h4><%= link_to activity.owner.username, user_path(activity.owner.username) %></h4>
									<p><small><%= time_ago_in_words(activity.created_at) %> ago </small></p>
								</div>
							</div>
						</div>
						<div class="panel-body">
							<% case activity.trackable_type when "Post" %>
							<p><%= activity.trackable.content %></p>
							<% when "Friendship" %>
							<%= link_to activity.owner.username, user_path(activity.owner.username) %> is now friends with <%= link_to activity.recipient.username, user_path(activity.recipient.username) %>
							<% end %>
						</div>

					</div>	
				</div>
			</div>
		<% end %>
	<% end %>
<% end %>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" style="box-shadow: 1px 1px 40px 0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user %>
      <%= link_to current_user.username.to_s + "Book", root_path, class: "navbar-brand" %>
      <% else %>
      <%= link_to "RailsBook", root_path, class: "navbar-brand" %>
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "News Feed", activities_path %></li>
        <li><%= link_to "Peeps", users_path %></li>
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= gravatar_tag current_user.email, size:30 %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user.username) %></li>
            <li><%= link_to "Friends", "#" %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MediaBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    	<%= render 'layouts/header' %>
      
      <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for(type) %> fade-in" style="box-shadow: 2px 2px 10px 0px;border: 1px solid black;">
          <button class="close" data-dismiss="alert" >X</button>
          <%= message %>
        </div>
      <% end %> 
    </header>

    <section>
    <div class="container">
      <%= yield %>
    </div>
    </section>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>

	<div class="panel panel-info">
		<div class="panel-heading">
			Posts
		</div>
		<div class="panel-body">
			<%= f.error_notification %>
			<%= f.input :content, required: true, label: false, placeholder: "Go ahead.... tell us about that sandwich you just ate. We really care.", input_html: {class: "form_control"} %>
		</div>
		<div class="panel-footer">
			<%= f.button :submit, class: "btn btn-primary btn-block" %>
		</div>
	</div>

<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<%= gravatar_tag post.user.email, size: 20 %> <%= post.user.username %> posted this <%= time_ago_in_words(post.created_at) %> ago
		<% if current_user == post.user %>
			<%= link_to "edit", edit_post_path(post) %> | <%= link_to "x", post, method: :delete %>
		<% end %>
	</div>
	<div class="panel-body">
		<%= post.content %>
	</div>


</div>

app/views/posts/edit.html.erb
<div class="container">

<%= render 'form' %>

</div>

app/views/public_activity/friendship/_accepted.html.erb
<% if activity.trackable %>
	<p><%= link_to activity.owner.username, user_path(activity.owner.username) %> is now Friends with <%= link_to activity.recipient.username, user_path(activity.recipient.username) %></p>
<% end %>

app/views/public_activity/post/_created.html.erb
<% if activity.trackable %>

	<p><%= time_ago_in_words(activity.created_at) %> ago, <%= link_to activity.owner.username, user_path(activity.owner.username) %> posted something...</p>

<% end %>

app/views/users/_user.html.erb
<div class="col-md-3">
	<div class="thumbnail" style="box-shadow: 2px 3px 7px 0px rgba(0,0,0,0.5);">
		<%= link_to user_path(user.username) do %>
			<%= gravatar_tag user.email, size: 300 %>
		<% end %>
		<div class="caption">
			<h3><%= user.username %></h3>
			<p><%= friend_buttons(user) %></p>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="jumbotron text-center">
<h2>Peeps!</h2>
	<div class="btn-group" role="group" aria-label="People Groups">
	<%= link_to "All", users_path, class: "btn btn-default #{'active' unless params[:people]}" %>
	<%= link_to "My Friends", users_path(people: "friends"), class: "btn btn-default #{'active' if params[:people] == "friends"}" %>
	<%= link_to "Requests", users_path(people: "requests"), class: "btn btn-default #{'active' if params[:people] == "requests"}" %>
	<%= link_to "Pending", users_path(people: "pending"), class: "btn btn-default #{'active' if params[:people] == "pending"}" %>
	</div>
</div>

<div class="container">
	<div class="row">
		<%= render @users %>
	</div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<%= gravatar_tag @user.email, size: 300 %>
			</div>
		</div>
	</div>	
</div>
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h3><%= @user.username %></h3>
			<p>Name: <%= @user.name %></p>
			<p>Age: <%= @user.age %></p>
			<p>School: <%= @user.school %></p>
			<p>Work: <%= @user.work %></p>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h3>About Me </h3>
			<small><%= @user.bio %></small>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					Friends (<%= @user.active_friends.size %>)
				</div>
				<div class="panel-body">
					<% @user.active_friends.last(16).each do |user| %>
						<%= link_to user_path(user.username) do %>
							<%= gravatar_tag user.email, size: 40 %>
						<% end %>
					<% end %>
				</div>	
			</div>
		</div>

		<div class="col-md-6">
			<% if current_user == @user %>
				<%= render 'posts/form' %>
			<% end %>
			<%= render @posts %>
		</div>

		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					Recent Activity
				</div>
				<div class="panel-body">
					<%= render_activities(@activities) %>
				</div>
			</div>
		</div>

	</div> 
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>